name: Build GHDL and OSVVM

on:
  push:
    paths:
      - '**.vhd'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and extract
        run: docker build --target=export --output=./artifacts .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ghdl-7-dev
          path: ./artifacts/ghdl-7-dev
